networks:
    proxy:
        external: true

services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: php.${APP_NAME}
        restart: unless-stopped
        volumes:
            - .:/var/www
        working_dir: /var/www
        ports:
            - "8000:8000"
        networks:
            - proxy

    node:
        image: node:latest
        container_name: node.${APP_NAME}
        restart: unless-stopped
        ports:
            - "5173:5173"
        volumes:
            - ./:/var/www
        working_dir: /var/www
        entrypoint: /var/www/docker/scripts/node.sh
        depends_on:
            - app
        networks:
            - proxy

